"""Neon/PostgreSQL storage with the same response shape as local SQLite."""

from datetime import datetime, timezone

import psycopg
from psycopg.rows import dict_row


def connect(database_url):
    if not isinstance(database_url, str) or not database_url.startswith(
        ("postgresql://", "postgres://")
    ):
        raise RuntimeError(
            "Set DATABASE_URL to the PostgreSQL connection string from Neon."
        )
    return psycopg.connect(database_url, connect_timeout=15, row_factory=dict_row)


def initialize_database(database_url):
    # CREATE IF NOT EXISTS preserves history on restarts and redeployments.
    with connect(database_url) as database:
        database.execute(
            """
            CREATE TABLE IF NOT EXISTS calculation_history (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                expression TEXT NOT NULL,
                result TEXT NOT NULL,
                created_at TEXT NOT NULL
            )
            """
        )


def save_history(database_url, expression, result):
    created_at = datetime.now(timezone.utc).isoformat()
    with connect(database_url) as database:
        record = database.execute(
            "INSERT INTO calculation_history (expression, result, created_at) "
            "VALUES (%s, %s, %s) RETURNING id, expression, result, created_at",
            (expression, result, created_at),
        ).fetchone()
    # Exit the connection context (commit) before reporting success.
    return dict(record)


def get_history(database_url, limit, offset):
    with connect(database_url) as database:
        database.execute(
            "SET TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY"
        )
        total = database.execute(
            "SELECT COUNT(*) AS total FROM calculation_history"
        ).fetchone()["total"]
        records = database.execute(
            "SELECT id, expression, result, created_at "
            "FROM calculation_history ORDER BY id DESC LIMIT %s OFFSET %s",
            (limit, offset),
        ).fetchall()
    return {
        "success": True,
        "records": [dict(record) for record in records],
        "total": total,
        "limit": limit,
        "offset": offset,
    }


def delete_history(database_url, history_id):
    with connect(database_url) as database:
        deleted = database.execute(
            "DELETE FROM calculation_history WHERE id = %s", (history_id,)
        ).rowcount > 0
    return deleted
